apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wdtz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wdtz
    app.kubernetes.io/part-of: byoc-app-zudz
  name: wdtz
spec:
  rules:
  - host: wdtz-byoc-yshh-tenant.apps.f5209be3162c1475a77e.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: wdtz
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
