apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wdtz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wdtz
    app.kubernetes.io/part-of: byoc-app-zudz
  name: wdtz
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: wdtz
status:
  loadBalancer: {}
